import { test, expect, login, send, slash } from './fixtures'

test('password login, new thread and streamed final item keep one user message', async ({ page, mock }) => {
  mock.holdFinalMessage = true
  await page.goto('/')
  await page.locator('input[type="password"]').first().fill('wrong-password')
  await page.getByRole('button', { name: /登录|进入工作区|解锁/ }).first().click()
  await expect(page.getByText('Incorrect password')).toBeVisible()
  await page.locator('input[type="password"]').first().fill('test-password-123')
  await page.getByRole('button', { name: /登录|进入工作区|解锁/ }).first().click()
  await expect(page.getByRole('textbox', { name: '消息输入框' })).toBeEnabled()
  await send(page, '创建一个测试任务')
  await expect(page.locator('.agent-message')).toContainText('流式回复')
  await expect(page.getByRole('button', { name: '停止生成', exact: true })).toBeVisible()
  mock.finishStream()
  await expect(page.locator('.agent-message')).toContainText('流式回复完成 ✅')
  await expect(page.getByText('上下文 20%', { exact: true })).toBeVisible()
  await expect(page.locator('.user-message')).toHaveCount(1)
  expect(mock.request('thread/start')?.params.cwd).toBe('/workspace/demo')
  expect(mock.request('turn/start')?.params.input[0]).toMatchObject({ type: 'text', text: '创建一个测试任务', text_elements: [] })
  await expect(page.getByRole('button', { name: '发送消息', exact: true })).toBeVisible()
})

test('model and permission selections reach app-server turn params', async ({ page, mock }) => {
  await login(page)
  await page.getByRole('combobox', { name: '选择模型' }).selectOption('mock-model-b')
  await page.getByRole('combobox', { name: '推理强度' }).selectOption('high')
  await page.getByRole('combobox', { name: '选择权限' }).selectOption('read-only')
  await send(page, '只读查看项目')
  await expect(page.locator('.agent-message')).toContainText('流式回复完成')
  expect(mock.request('thread/start')?.params).toMatchObject({ model: 'mock-model-b', sandbox: 'read-only' })
  expect(mock.request('turn/start')?.params).toMatchObject({ model: 'mock-model-b', effort: 'high', approvalPolicy: 'on-request', sandboxPolicy: { type: 'readOnly', networkAccess: false } })
})

test('input during an active turn steers the same turn and keeps both user messages', async ({ page, mock }) => {
  mock.holdFinalMessage = true
  await login(page)
  await send(page, '开始长任务')
  await expect(page.locator('.agent-message')).toContainText('流式回复')
  const initial = mock.request('turn/start')!
  await page.getByRole('textbox', { name: '消息输入框' }).fill('追加一个约束')
  await page.getByRole('textbox', { name: '消息输入框' }).press('Enter')
  await expect.poll(() => mock.request('turn/steer')?.params.threadId).toBe(initial.params.threadId)
  await expect(page.locator('.user-message')).toHaveCount(2)
  expect(mock.requests.filter(request => request.method === 'turn/start')).toHaveLength(1)
  expect(mock.request('turn/steer')?.params.input[0].text).toBe('追加一个约束')
  mock.finishStream()
  await expect(page.locator('.agent-message')).toContainText('流式回复完成 ✅')
})

test('fork keeps history and sends subsequent input to the new thread', async ({ page, mock }) => {
  await login(page)
  await send(page, '准备分支')
  await expect(page.locator('.agent-message')).toContainText('流式回复完成')
  const source = mock.request('turn/start')?.params.threadId
  await slash(page, 'fork')
  await expect.poll(() => mock.request('thread/fork')?.params.threadId).toBe(source)
  await expect(page.locator('.agent-message')).toContainText('流式回复完成')
  await send(page, '仅在分支里继续')
  await expect(page.locator('.agent-message')).toHaveCount(2)
  expect(mock.request('turn/start')?.params.threadId).toMatch(/^fork-/)
  expect(mock.turns.get(source)).toHaveLength(1)
})

test('manual slash compaction and threshold-triggered automatic compaction use protocol', async ({ page, mock }) => {
  await login(page)
  await send(page, '先创建会话')
  await expect(page.locator('.agent-message')).toContainText('流式回复完成')
  await slash(page, 'compact')
  await expect(page.locator('.compaction-divider')).toContainText('上下文已压缩')
  expect(mock.request('thread/compact/start')?.params.threadId).toBe(mock.request('turn/start')?.params.threadId)
  mock.contextTokens = 900
  await send(page, '触发压缩阈值')
  await expect.poll(() => mock.requests.filter(request => request.method === 'thread/compact/start').length).toBe(2)
  await expect(page.locator('.compaction-divider')).toHaveCount(2)
})

test('server approval pauses the turn, responds with original id and clears prompt', async ({ page, mock }) => {
  mock.requireApprovalNext = true
  await login(page)
  await send(page, '需要审批的测试')
  const approval = page.getByRole('region', { name: '批准命令执行' })
  await expect(approval).toContainText('printf approved')
  await expect(page.getByRole('button', { name: '停止生成', exact: true })).toBeVisible()
  await approval.getByRole('button', { name: '允许一次', exact: true }).click()
  await expect(approval).toHaveCount(0)
  await expect(page.locator('.agent-message')).toContainText('审批后继续工作')
  expect(mock.responses.at(-1)).toMatchObject({ id: 'approval-2', result: { decision: 'accept' } })
})

test('slash commands and @ file lookup work through keyboard selection', async ({ page, mock }) => {
  await login(page)
  const input = page.getByRole('textbox', { name: '消息输入框' })
  await input.fill('@READ')
  await expect(page.getByRole('listbox', { name: '项目文件' })).toBeVisible()
  await expect(page.getByRole('option').filter({ hasText: 'README.md' })).toBeVisible()
  await input.press('Enter')
  await expect(input).toHaveValue('@/workspace/demo/README.md ')
  expect(mock.request('fuzzyFileSearch')?.params).toMatchObject({ query: 'READ', roots: ['/workspace/demo'] })
  await input.fill('/new')
  await expect(page.getByRole('listbox', { name: '对话指令' })).toBeVisible()
  await input.press('Enter')
  await expect(input).toHaveValue('')
  await page.keyboard.press('Control+k')
  await expect(page.getByRole('dialog')).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).toHaveCount(0)
})

test('file and image uploads carry host/cwd and generate localImage + file references', async ({ page, mock }) => {
  await login(page)
  await page.locator('input[type="file"]').setInputFiles([
    { name: 'sample.png', mimeType: 'image/png', buffer: Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO7+UqsAAAAASUVORK5CYII=', 'base64') },
    { name: 'notes.txt', mimeType: 'text/plain', buffer: Buffer.from('hello') },
  ])
  await expect(page.locator('.attachment')).toHaveCount(2)
  expect(mock.uploads).toHaveLength(1)
  expect(mock.uploads[0].contentType).toContain('multipart/form-data; boundary=')
  const body = mock.uploads[0].body.toString('utf8')
  expect(body).toContain('name="hostId"\r\n\r\nlocal')
  expect(body).toContain('name="cwd"\r\n\r\n/workspace/demo')
  expect(body).toContain('filename="sample.png"')
  await send(page, '请查看附件')
  await expect(page.locator('.agent-message')).toContainText('流式回复完成')
  const inputs = mock.request('turn/start')?.params.input
  expect(inputs).toContainEqual({ type: 'localImage', path: '/test/uploads/sample.png' })
  expect(inputs[0].text).toContain('附件文件：/test/uploads/notes.txt（notes.txt）')
  await expect(page.locator('.attachment')).toHaveCount(0)
})

test('terminal handles byte-split Unicode output and stdin through app-server', async ({ page, mock }) => {
  await login(page)
  await slash(page, 'terminal')
  await expect(page.getByRole('button', { name: '结束终端', exact: true })).toBeEnabled()
  await page.getByRole('button', { name: '结束终端', exact: true }).click()
  await page.getByRole('button', { name: '命令模式', exact: true }).click()
  const input = page.getByRole('textbox', { name: '终端命令' })
  await input.fill('echo test')
  await input.press('Enter')
  await expect(page.locator('.terminal-output')).toContainText('终端输出正常')
  expect(mock.request('command/exec')?.params).toMatchObject({ command: ['/bin/sh', '-lc', 'echo test'], cwd: '/workspace/demo', streamStdoutStderr: true, streamStdin: true })
  await input.fill('下一行')
  await input.press('Enter')
  await expect.poll(() => mock.request('command/exec/write')?.params.deltaBase64).toBe(Buffer.from('下一行\n').toString('base64'))
  await page.getByRole('button', { name: '结束进程' }).click()
  await expect(page.locator('.terminal-output')).toContainText('[进程退出 0]')
})

test('HTML file preview runs in opaque sandbox and cannot access parent DOM', async ({ page }) => {
  await login(page)
  await slash(page, 'terminal')
  await page.getByRole('button', { name: '预览', exact: true }).click()
  await page.getByRole('textbox', { name: '预览地址' }).fill('index.html')
  await page.getByRole('button', { name: '打开预览', exact: true }).click()
  const frame = page.locator('iframe[title="项目预览"]')
  await expect(frame).toBeVisible()
  await expect(frame).not.toHaveAttribute('sandbox', /allow-same-origin/)
  await expect(page.frameLocator('iframe[title="项目预览"]').locator('#status')).toHaveText('isolated')
  expect(await page.evaluate(() => document.body.dataset.previewEscape)).toBeUndefined()
  await expect(frame).toHaveAttribute('src', /host=local.*path=%2Fworkspace%2Fdemo%2Findex.html/)
})

test('PTY shell sends stdin, resize and termination using connection process id', async ({ page, mock }) => {
  await login(page)
  await slash(page, 'terminal')
  await expect(page.getByLabel('交互式终端')).toBeVisible()
  await expect.poll(() => mock.request('command/exec')?.params.tty).toBe(true)
  const processId = mock.request('command/exec')?.params.processId
  expect(mock.request('command/exec')?.params).toMatchObject({ command: ['/bin/sh'], cwd: '/workspace/demo', disableTimeout: true })
  await page.locator('.xterm-helper-textarea').focus()
  await page.keyboard.type('echo tty')
  await expect.poll(() => mock.requests.filter(request => request.method === 'command/exec/write').map(request => Buffer.from(request.params.deltaBase64, 'base64').toString()).join('')).toContain('echo tty')
  await page.setViewportSize({ width: 1440, height: 1000 })
  await expect.poll(() => mock.request('command/exec/resize')?.params.processId).toBe(processId)
  expect(mock.request('command/exec/resize')?.params.size.cols).toBeGreaterThan(0)
  await page.getByRole('button', { name: '结束终端', exact: true }).click()
  await expect.poll(() => mock.request('command/exec/terminate')?.params.processId).toBe(processId)
  await expect(page.getByRole('button', { name: '启动终端', exact: true })).toBeEnabled()
})

test('390px mobile layout supports composer, approval and workspace without page overflow', async ({ page, mock }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  mock.requireApprovalNext = true
  await login(page)
  await expect(page.getByRole('textbox', { name: '消息输入框' })).toBeInViewport()
  await send(page, '移动端审批')
  const approval = page.getByRole('region', { name: '批准命令执行' })
  await approval.getByRole('button', { name: '拒绝', exact: true }).click()
  await expect(page.locator('.agent-message')).toContainText('操作已拒绝')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1)).toBe(true)
  await slash(page, 'terminal')
  await page.getByRole('button', { name: '命令模式', exact: true }).click()
  await expect(page.getByRole('textbox', { name: '终端命令' })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1)).toBe(true)
})
